language: elixir
cache:
  directories:
  - deps
elixir:
  - 1.3.0
otp_release:
  - 19.0
env:
  global:
    - MIX_ENV=test
script:
  # - "./bin/version_increment.sh" # Uncomment this if you want to increment patch version on each Travis build.
  - "mix deps.get"
  - "mix test --trace"
  - "mix coveralls.travis"
  - "mix credo"
  - "mix dogma"
# after_success:

# Uncomment this if you want to push mix.exs with incremented back to origin repo.
#   - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
#       echo "Done. Commiting changes back to repo.";
#       git add mix.exs;
#       git commit -m "Increment version [ci skip]";
#       git push origin HEAD:$TRAVIS_BRANCH;
#       git push origin --tags;
#     fi;
